@ProjetoAPI01_HostAddress = http://localhost:5143

POST {{ProjetoAPI01_HostAddress}}/api/usuarios/login
Content-Type: application/json
Accept: application/json

{
  "email": "elma@aluno.senaisp.br",
  "senha": "maria"
}